name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake

    - name: Install dependencies
      run: |
        sudo apt-get install -y libgtest-dev

    - name: Build and run tests
      run: |
        mkdir build
        cd build
        cmake ..
        make
        ./MatrixTests

