name: Build and Test

on:
  push:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest  # Replace with desired runner (e.g., macos-latest)
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake
      - name: Clone Google Test
        run: |
          git clone https://github.com/google/googletest.git
      - name: Build Google Test
        working-directory: googletest
        run: |
          mkdir build
          cd build
          cmake .. -DBUILD_GMOCK=OFF
          make
      - name: Build project
        run: cmake .
      - name: Run tests
        run: make
