name: Google Test

on: [push, pull_request]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y libgtest-dev cmake

    - name: Build
      run: |
        cmake .
        make

    - name: Test
      run: ./path-to-your-test-executable
