name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nvidia/cuda:12.0-base-ubuntu22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y git cmake g++
        git clone https://github.com/google/googletest.git
        cd googletest
        mkdir build
        cd build
        cmake .. -DBUILD_GMOCK=OFF
        make

    - name: Build and run tests
      run: |
        mkdir build
        cd build
        cmake ..
        make
        ./matrixTest
