name: Build and Test (CUDA)

on:
  push:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest  # Replace with desired runner (e.g., macos-latest)
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake
      - name: Install CUDA Toolkit (if missing)
        run: |
          if ! command -v nvcc &> /dev/null; then
            # Use existing action for CUDA Toolkit installation
            steps:
              - uses: Jimver/cuda-toolkit@v0.2.14
                id: cuda-toolkit
                with:
                  cuda: '12.0'

            # Print information about installed CUDA toolkit
            - run: echo "Installed cuda version is: ${{ steps.cuda-toolkit.outputs.cuda }}"
            - run: echo "Cuda install location: ${{ steps.cuda-toolkit.outputs.CUDA_PATH }}"
            - run: nvcc -V
          fi
      - name: Clone Google Test
        run: |
          git clone https://github.com/google/googletest.git
      - name: Build Google Test
        working-directory: googletest
        run: |
          mkdir build
          cd build
          cmake .. -DBUILD_GMOCK=OFF
          make
      - name: Build project
        env:
          # Set environment variable for CUDA toolkit (if installed)
          CUDAToolkit_ROOT=${HOME}/cuda  # Replace with your actual install path
        run: cmake .
      - name: Run tests
        run: make
