name: Build and Test

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - name: Set up CUDA Toolkit
      # - uses: Jimver/cuda-toolkit@v0.2.14
      #   with:
      #     cuda: '12.3.2'
      # - run: nvcc -V
      
      - name: Install Google Test
        run: |
          git clone https://github.com/google/googletest.git
          cd googletest
          mkdir build
          cd build
          cmake .. -DBUILD_GMOCK=OFF
          make
          cd ../../

      - name: Build and test the project
        run: |
          cmake .
          make
          ./matrixTest

